version: '3.8'

services:
  wuzapi-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - WUZAPI_ADMIN_TOKEN=${WUZAPI_ADMIN_TOKEN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./dbdata:/app/dbdata
      - ./files:/app/files
    networks:
      - wuzapi-network

networks:
  wuzapi-network:
    driver: bridge

volumes:
  dbdata:
  files:
  db_data:
